config/routes.rb
Rails.application.routes.draw do

  resources :productos
  root 'sesion#login'

  resources :usuarios
  resources :clientes

  resources :sesion, :only => [:crear, :destruir, :login]

  get '/login' => 'sesion#login'
  post '/login' => 'sesion#crear'
  get '/logout' => 'sesion#destruir'

  get '/home' => 'menu#index'

  get 'usuarios/new' => 'usuario#new'
  get 'usuarios' => 'usuario#index'
  get 'Admin' => 'usuario#index'
  get 'productos' => 'productos#index'

  get 'gestion' => 'menu#index'

  get 'cotizaciones' => 'menu#index'
  get 'cotizaciones/administrar' => 'cotizaciones#administrar'
  get 'cotizaciones/selCliente'
  get 'cotizaciones/buscarCliente' => 'cotizaciones#buscarCliente'

  get 'clientes' => 'clientes#index'
  get 'clientes/new' => 'clientes#new'
  post 'clientes/create' => 'clientes#create'

  get 'cotizaciones/buscarProd'
  get 'cotizaciones/agregarProd'
  get 'cotizaciones/cambiarCantidad'
  get 'cotizaciones/actualizar'
  get 'cotizaciones/salir' => 'cotizaciones#salir'
  get 'cotizaciones/buscar'

  get 'cotizaciones/estadisticas' => 'cotizaciones#estadisticas'

  post 'cotizaciones/administrar' => 'cotizaciones#actualizar'

  get 'cotizaciones/eliminar' => 'cotizaciones#eliminarCot'
  get 'cotizaciones/enviarCorreo' => 'cotizaciones#enviarCorreo'

  get 'gestion/listados' => 'gestion#listados'
  get 'gestion/informes' => 'gestion#informes'
  get '/gestion/mostrarListado' => 'gestion#mostrarListado'

  get '/cotizaciones/imprimir' => 'cotizaciones#imprimir'

  get '/verificarCotizacion/:id', to:'cotizaciones#confirmar'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
  self.primary_key = 'rut'
  validates :rut, presence:{:message => "no puede estar vacio"}, uniqueness:{:message => " ya existe en la base de datos"}, rut:{:message => " no es valido"}
  validates :email, email:{:message => "invalido"}

end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController

  before_action :set_cliente, only: [:show]
  def index
    @clientes = Cliente.all
  end

  def show
  end

  def new
    @cliente = Cliente.new
  end

  def create
    @cliente = Cliente.new(cliente_params)
    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente agregado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def set_cliente
    @cliente = Cliente.find(params[:id])
  end
  def cliente_params
    params.require(:cliente).permit(:rut,:nombres,:direccion,:ciudad,:comuna,:telefono,:fax,:email)
  end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/clientes/index.html.erb
<table>
  <thead>
  <tr>
    <th>Rut</th>
    <th>Nombre</th>
    <th>Direccion</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @clientes.each do |c| %>
      <tr>
        <td><%= c.rut %></td>
        <td><%= c.nombres %></td>
        <td><%= c.direccion %></td>
        <td><%# usuario.ultimo_login %></td>
        <td><%= link_to 'Mostrar', cliente %></td>
        <td><%= link_to 'Editar', edit_cliente_path(usuario) %></td>
        <td><%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Esta Seguro?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>


<br>

<%= link_to 'Nuevo Usuario', new_cliente_path %><br>
<%= link_to 'Volver', 'home' %>

app/views/clientes/new.html.erb
<div class ="container">
<div class ="col-md-5">
  <div class="form-area">
  <h1>Registrar nuevo cliente</h1>
  <%= form_for @cliente do |f| %>
      <% if @cliente.errors.any? %>
        <div id="error_explanation" class = "row">
          <h2><%= pluralize(@cliente.errors.count, "errores") %> prohibieron la creación de este cliente:</h2>

          <ul>
          <% @cliente.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%# f.label :rut%>
        <%= f.text_field :rut , class:"form-control" , placeholder:"Rut(Sin puntos)"%>
      </div>
      <div>
        <%# f.label :nombres%>
        <%= f.text_field :nombres , class:"form-control" , placeholder:"Nombres"%>
      </div>
      <div>
        <%# f.label :direcion%>
        <%= f.text_field :direccion, class:"form-control" , placeholder:"Dirección" %>
      </div>
      <div>
        <%# f.label :ciudad%>
        <%= f.text_field :ciudad, class:"form-control" , placeholder:"Ciudad" %>
      </div>
      <div>
        <%# f.label :comuna%>
        <%= f.text_field :comuna, class:"form-control" , placeholder:"Comuna" %>
      </div>
      <div>
        <%# f.label :telefono%>
        <%= f.text_field :telefono, class:"form-control" , placeholder:"Telefono" %>
      </div>
      <div>
        <%# f.label :fax%>
        <%= f.text_field :fax, class:"form-control" , placeholder:"Fax" %>
      </div>
      <div>
        <%# f.label :email%>
        <%= f.text_field :email, class:"form-control" , placeholder:"E-mail" %>
      </div>
      <%= f.submit "Guardar", class:"btn btn-primary pull-right"%>
  <%end %>
  <%= link_to "Volver", '/home', class:"btn btn-default pull-left"%>
  </div>
  </div>
</div>

app/views/clientes/show.html.erb
<div class="container text-center img-rounded col-xs-4 col-xs-offset-4" style="background-color: lightblue;">
	<div class="row">
		<h3 id="notice"><%= notice %></h3>
	</div>
	<div class="row text-center">
		<p>
		  <strong>Rut:</strong>
		  <%= @cliente.rut %>
		</p>

		<p>
		  <strong>Nombre:</strong>
		  <%= @cliente.nombres %>
		</p>

		<p>
		  <strong>Direccion:</strong>
		  <%= @cliente.direccion %>
		</p>
	</div>
	<%# link_to 'Editar', edit_cliente_path(@usuario) %> 
	<%= link_to 'Volver', '/home', class:"btn btn-primary block-center", style:"color:white;"%>
</div>