config/routes.rb
Rails.application.routes.draw do

  resources :productos
  root 'sesion#login'

  resources :usuarios
  resources :clientes

  resources :sesion, :only => [:crear, :destruir, :login]

  get '/login' => 'sesion#login'
  post '/login' => 'sesion#crear'
  get '/logout' => 'sesion#destruir'

  get '/home' => 'menu#index'

  get 'usuarios/new' => 'usuario#new'
  get 'usuarios' => 'usuario#index'
  get 'Admin' => 'usuario#index'
  get 'productos' => 'productos#index'

  get 'gestion' => 'menu#index'

  get 'cotizaciones' => 'menu#index'
  get 'cotizaciones/administrar' => 'cotizaciones#administrar'
  get 'cotizaciones/selCliente'
  get 'cotizaciones/buscarCliente' => 'cotizaciones#buscarCliente'

  get 'clientes' => 'clientes#index'
  get 'clientes/new' => 'clientes#new'
  post 'clientes/create' => 'clientes#create'

  get 'cotizaciones/buscarProd'
  get 'cotizaciones/agregarProd'
  get 'cotizaciones/cambiarCantidad'
  get 'cotizaciones/actualizar'
  get 'cotizaciones/salir' => 'cotizaciones#salir'
  get 'cotizaciones/buscar'

  get 'cotizaciones/estadisticas' => 'cotizaciones#estadisticas'

  post 'cotizaciones/administrar' => 'cotizaciones#actualizar'

  get 'cotizaciones/eliminar' => 'cotizaciones#eliminarCot'
  get 'cotizaciones/enviarCorreo' => 'cotizaciones#enviarCorreo'

  get 'gestion/listados' => 'gestion#listados'
  get 'gestion/informes' => 'gestion#informes'
  get '/gestion/mostrarListado' => 'gestion#mostrarListado'

  get '/cotizaciones/imprimir' => 'cotizaciones#imprimir'

  get '/verificarCotizacion/:id', to:'cotizaciones#confirmar'

end

app/models/producto.rb
class Producto < ActiveRecord::Base
	 	has_many :producto_cotizacions
		has_many :cotizacions, through: :producto_cotizacions
		validates :descuento, numericality:{only_integer:true, greater_than_or_equal_to:0,less_than:101}
		validates :valor_unitario, numericality:{only_integer:true, greater_than:0}
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: [:show, :edit, :update, :destroy]

  # GET /productos
  # GET /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1
  # GET /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos
  # POST /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: 'Producto was successfully created.' }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1
  # PATCH/PUT /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: 'Producto was successfully updated.' }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1
  # DELETE /productos/1.json
  def destroy
    @producto.destroy
    respond_to do |format|
      format.html { redirect_to productos_url, notice: 'Producto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producto_params
      params.require(:producto).permit(:codigo, :descripcion, :valor_unitario, :descuento, :stock, :estado)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_for(@producto) do |f| %>
  <% if @producto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
      <% @producto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br>
    <%= f.number_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :valor_unitario %><br>
    <%= f.number_field :valor_unitario %>
  </div>
  <div class="field">
    <%= f.label :descuento %><br>
    <%= f.number_field :descuento %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/productos/edit.html.erb
<h1>Editing Producto</h1>

<%= render 'form' %>

<%= link_to 'Show', @producto %> |
<%= link_to 'Back', productos_path %>

app/views/productos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Productos</h1>

<table>
  <thead>
    <tr>
      <th>Codigo</th>
      <th>Descripcion</th>
      <th>Valor unitario</th>
      <th>Descuento</th>
      <th>Stock</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @productos.each do |producto| %>
      <tr>
        <td><%= producto.codigo %></td>
        <td><%= producto.descripcion %></td>
        <td><%= producto.valor_unitario %></td>
        <td><%= producto.descuento %></td>
        <td><%= producto.stock %></td>
        <td><%= producto.estado %></td>
        <td><%= link_to 'Show', producto %></td>
        <td><%= link_to 'Edit', edit_producto_path(producto) %></td>
        <td><%= link_to 'Destroy', producto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producto', new_producto_path %>
<%= link_to 'Volver', '/home' %>

app/views/productos/new.html.erb
<h1>New Producto</h1>

<%= render 'form' %>

<%= link_to 'Back', productos_path %>

app/views/productos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Codigo:</strong>
  <%= @producto.codigo %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @producto.descripcion %>
</p>

<p>
  <strong>Valor unitario:</strong>
  <%= @producto.valor_unitario %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @producto.stock %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @producto.estado %>
</p>

<%= link_to 'Edit', edit_producto_path(@producto) %> |
<%= link_to 'Back', productos_path %>