config/routes.rb
Rails.application.routes.draw do

  resources :productos
  root 'sesion#login'

  resources :usuarios
  resources :clientes

  resources :sesion, :only => [:crear, :destruir, :login]

  get '/login' => 'sesion#login'
  post '/login' => 'sesion#crear'
  get '/logout' => 'sesion#destruir'

  get '/home' => 'menu#index'

  get 'usuarios/new' => 'usuario#new'
  get 'usuarios' => 'usuario#index'
  get 'Admin' => 'usuario#index'
  get 'productos' => 'productos#index'

  get 'gestion' => 'menu#index'

  get 'cotizaciones' => 'menu#index'
  get 'cotizaciones/administrar' => 'cotizaciones#administrar'
  get 'cotizaciones/selCliente'
  get 'cotizaciones/buscarCliente' => 'cotizaciones#buscarCliente'

  get 'clientes' => 'clientes#index'
  get 'clientes/new' => 'clientes#new'
  post 'clientes/create' => 'clientes#create'

  get 'cotizaciones/buscarProd'
  get 'cotizaciones/agregarProd'
  get 'cotizaciones/cambiarCantidad'
  get 'cotizaciones/actualizar'
  get 'cotizaciones/salir' => 'cotizaciones#salir'
  get 'cotizaciones/buscar'

  get 'cotizaciones/estadisticas' => 'cotizaciones#estadisticas'

  post 'cotizaciones/administrar' => 'cotizaciones#actualizar'

  get 'cotizaciones/eliminar' => 'cotizaciones#eliminarCot'
  get 'cotizaciones/enviarCorreo' => 'cotizaciones#enviarCorreo'

  get 'gestion/listados' => 'gestion#listados'
  get 'gestion/informes' => 'gestion#informes'
  get '/gestion/mostrarListado' => 'gestion#mostrarListado'

  get '/cotizaciones/imprimir' => 'cotizaciones#imprimir'

  get '/verificarCotizacion/:id', to:'cotizaciones#confirmar'

end

app/models/usuario.rb
class Usuario < ActiveRecord::Base

  has_secure_password

  validates :password, length: {minimum: 8}
  validates :rut, presence:true, uniqueness:{:message => "ya existe en base de datos"}, rut:{:message => "no es valido"}


end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  if Rails.env.production?
    before_filter :authorize, :only => [:new, :create, :index, :edit, :show, :destroy]
  end
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    #if(current_user.privilegios < 4)
    #  redirect_to '/home'
    #end
    @usuarios = Usuario.all

  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        #session[:id] = @usuario.id
        format.html { redirect_to @usuario, notice: 'Usuario creado satisfactoriamente.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)

        format.html { redirect_to @usuario, notice: 'Usuario actualizado satisfactoriamente.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario eliminado satisfactoriamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:rut, :nombre, :password, :privilegios, :ultimo_login)
    end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "errores") %> prohibieron la creación de este usuario:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rut %><br>
    <%= f.text_field :rut %>
  </div>
    <div class="field">
      <%= f.label :nombre %><br>
      <%= f.text_field :nombre %>
    </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :privilegios %><br>
    <%= f.text_field :privilegios %>
  </div>
  <div class="actions">
    <% if flash[:edit] %>
         <%= f.submit "Guardar Usuario", class:"btn btn-primary" %>
    <%else%>
        <%= f.submit "Crear Usuario",class:"btn btn-primary"%>
    <%end %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>
<% flash[:edit] = true %>
<%= render 'form' %>

<%= link_to 'Mostrar', @usuario %> |
<%= link_to 'Volver', usuarios_path %>

app/views/usuarios/index.html.erb
<div id="container">
  <div id="row">
    <p id="notice"><%= notice %></p>
  </div>
  <div id="row">
    <h1 class="text-center">Lista de Usuarios</h1>
  </div>

    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th>Rut</th>
          <th>Nombre</th>
          <th>Privilegios</th>
          <th>Ultimo login</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @usuarios.each do |usuario| %>
          <tr>
            <td><%= usuario.rut %></td>
            <td><%= usuario.nombre %></td>
            <td align="center"><%= usuario.privilegios %></td>
            <td><%= usuario.ultimo_login %></td>
            <td><%= link_to 'Mostrar', usuario , class:"btn btn-primary btn-xs center-block", style:"color:white;"%></td>
            <td><%= link_to 'Editar', edit_usuario_path(usuario), class:"btn btn-primary btn-xs center-block", style:"color:white;" %></td>
            <td><%= link_to 'Eliminar', usuario, method: :delete, data: { confirm: 'Esta Seguro?' } , class:"btn btn-primary btn-xs center-block", style:"color:white;"%></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>
  <div id="row ">
    <%= link_to 'Nuevo Usuario', new_usuario_path ,class:"btn btn-primary col-xs-offset-5", style:"color:white;"%>
    <%= link_to 'Volver', 'home' ,class:"btn btn-primary ", style:"color:white;"%>
  </div>
</div>

app/views/usuarios/new.html.erb
<div class="panel">

<div class="panel-heading text-center col-xs-6 col-xs-offset-3">
<h1>Nuevo usuario</h1>
</div>
<div class="panel-body text-center col-xs-6 col-xs-offset-3">
<%= render 'form' %>

<%= link_to 'Volver', usuarios_path, class:"btn btn-primary", style:"color:white;" %>
</div>
</div>

app/views/usuarios/show.html.erb
<div class="panel">
<div class="panel-body text-center col-xs-6 col-xs-offset-3">
<p id="notice"><%= notice %></p>

<p>
  <strong>Rut:</strong>
  <%= @usuario.rut %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Privilegios:</strong>
  <%= @usuario.privilegios %>
</p>

<p>
  <strong>Ultimo Login:</strong>
  <%= @usuario.ultimo_login %>
</p>

<%= link_to 'Editar', edit_usuario_path(@usuario),class:"btn btn-primary btn-xs", style:"color:white;" %> |
<%= link_to 'Volver', usuarios_path, class:"btn btn-primary btn-xs", style:"color:white;" %>
</div>
</div>